# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: get all spec files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(find cypress/integration -type f -name "*.spec.js" | xargs -n2 | tr ' ' ',' | jq -R . | jq -s -cM .)"

  cypress-run:
    needs: job1
    runs-on: ubuntu-latest
    container: cypress/included:8.0.0 # this line specifies the docker image we want
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        containers: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: ${{matrix.containers}}
          start: npm start
      - uses: actions/upload-artifact@v1
        if: always() # / if: failure() <- more suitable for production
        with:
          name: cypress-videos
          path: cypress/videos
